### ISSUE TITLE
Dynamic refresh or update

### ISSUE THREAD

**Issue by HSeffouh1** [ubbn/wxPython#9]
Hi, got a form by WXGlade  / wxpython and willing to have fields set to be disabled based on combox values.
Struggling to have an approprite script for that.
any help guys please? 
@DietmarSchwertberger
![image](https://user-images.githubusercontent.com/53316053/103007160-35037600-4533-11eb-9e83-02ca4c46d7d4.png)

**Comment by DietmarSchwertberger** [comment]
Define an event handlers for the combobox. Then set a debugger breakpoint on the handler.
http://wxglade.sourceforge.net/docs/source_code.html#hints-and-tips

But for such questions please post to the wxGlade mailing list if it's wxGlade specific. If it's about wxPython in general, please go to https://discuss.wxpython.org/

**Comment by HSeffouh1** [comment]
> Define an event handlers for the combobox. Then set a debugger breakpoint on the handler.
> http://wxglade.sourceforge.net/docs/source_code.html#hints-and-tips
> 
> But for such questions please post to the wxGlade mailing list if it's wxGlade specific. If it's about wxPython in general, please go to https://discuss.wxpython.org/

Thanks @DietmarSchwertberger  for the tip, will take that in consideration in the future ;-)
now for the issue, yes i did that already and i just found out what was wrong, i should use wxEVT_COMBOBOX and not EVT_BUTTON :-)
